### ISSUE TITLE
Add build flow

### ISSUE THREAD

**Issue by YerkoPalma** [YerkoPalma/ui#1]
Maybe with aliasify and es6ify?

**Comment by YerkoPalma** [comment]
# TODO

- [x] Bundle correctly index.js
- [ ] Bundle all components in separate files
- [x] Add publish script
